# --- Build and start in the background ---
# docker compose up --build -d

# --- View logs ---
# docker compose logs -f

# --- Stop and remove ---
# docker compose down

# --- Build and push to Dockerhub ---
# docker compose build
# docker login
# docker compose push

version: "3.9"

services:
  autohub-server:
    image: dominicfernandez1023/autohub-server:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "5000:5000"
    env_file:
      - server/.env.prod
    environment:
      NODE_ENV: "production"
